import base64
import json
import logging
import os
from datetime import date
from typing import Optional
from dotenv import load_dotenv
import requests

from models import Receipt, ReceiptItem

# Load environment variables
load_dotenv()

NVIDIA_API_KEY = os.environ.get("NVIDIA_API_KEY", "")
NVIDIA_MODEL = os.environ.get("NVIDIA_MODEL", "meta/llama-3.2-11b-vision-instruct")
NVIDIA_MODEL_FALLBACK = os.environ.get("NVIDIA_MODEL_FALLBACK", "meta/llama-3.2-90b-vision-instruct")
NIM_ENDPOINT = "https://integrate.api.nvidia.com/v1/chat/completions"

logger = logging.getLogger("receipt_scanner")
logging.basicConfig(level=logging.INFO)

MERCHANT_MAP = {
    "wal-mart": "Walmart",
    "walmart supercenter": "Walmart",
    "walmart.com": "Walmart",
    "amzn mktp us": "Amazon",
    "amazon.com": "Amazon",
    "amzn": "Amazon",
    "target stores": "Target",
    "target store": "Target",
    "target.com": "Target",
    "costco wholesale": "Costco",
    "costco wholesale corp": "Costco",
    "sam's club": "Sam's Club",
    "sams club": "Sam's Club",
    "sams club store": "Sam's Club",
    "trader joe's": "Trader Joe's",
    "trader joes": "Trader Joe's",
    "whole foods market": "Whole Foods",
    "whole foods": "Whole Foods",
    "mcdonald's": "McDonald's",
    "starbucks coffee": "Starbucks",
    "starbucks": "Starbucks",
    "home depot": "The Home Depot",
    "the home depot": "The Home Depot",
    "best buy": "Best Buy",
    "walgreens": "Walgreens",
    "cvs pharmacy": "CVS",
    "cvs": "CVS",
}


def normalize_merchant(name: str) -> str:
    cleaned = name.strip()
    return MERCHANT_MAP.get(cleaned.lower(), cleaned)


def validate_totals(receipt: Receipt) -> bool:
    """Validate arithmetic: sum(items) + tax ≈ total. If mismatch, return False."""
    if receipt.subtotal is None or receipt.tax is None:
        return True  # not enough data to check, don't block on it
    item_sum = sum(i.price for i in receipt.items)
    calculated = receipt.subtotal + receipt.tax
    return abs(calculated - receipt.total) <= 0.02 and abs(item_sum - receipt.subtotal) <= 0.05


def clean_json_response(raw_text: str) -> str:
    """Remove markdown code blocks, reasoning/think tags, and isolate valid JSON string."""
    import re
    cleaned = raw_text.strip()
    # Remove <think>...</think> tags if generated by reasoning models
    cleaned = re.sub(r"<think>.*?</think>", "", cleaned, flags=re.DOTALL).strip()

    # Extract content inside markdown fences if present
    fence_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned)
    if fence_match:
        cleaned = fence_match.group(1).strip()

    # Extract JSON object between outermost braces
    if not (cleaned.startswith("{") and cleaned.endswith("}")):
        first_brace = cleaned.find("{")
        last_brace = cleaned.rfind("}")
        if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
            cleaned = cleaned[first_brace : last_brace + 1]

    return cleaned.strip()



def _call_nim_vision(key: str, model: str, image_b64: str, mime_type: str) -> str:
    """Call NIM vision endpoint and return raw response text."""
    prompt = (
        "Extract merchant, date, items (name, price, category), subtotal, "
        "tax, and total from this receipt image. Categories must be one of: Food, Groceries, "
        "Restaurant, Alcohol, Household, Electronics, Health, Transportation, "
        "Entertainment, Other. Return ONLY valid JSON matching this exact shape: "
        '{"merchant": "Store Name", "date": "YYYY-MM-DD", "total": 0.00, '
        '"subtotal": 0.00, "tax": 0.00, '
        '"items": [{"name": "Item Name", "price": 0.00, "category": "Groceries"}]}. '
        "No markdown fences, no explanation, valid JSON only."
    )

    payload = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": {"url": f"data:{mime_type};base64,{image_b64}"}}
                ],
            }
        ],
        "temperature": 0.1,
        "max_tokens": 1500,
    }

    headers = {
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
    }

    resp = requests.post(NIM_ENDPOINT, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()
    data = resp.json()
    return data["choices"][0]["message"]["content"]


def _render_pdf_first_page(pdf_path: str) -> str:
    """Render the first page of a PDF to a PNG file and return its path."""
    import pymupdf

    png_path = os.path.splitext(pdf_path)[0] + "_page.png"
    with pymupdf.open(pdf_path) as doc:
        page = doc[0]
        pix = page.get_pixmap(matrix=pymupdf.Matrix(2, 2))
        pix.save(png_path)
    return png_path


def _prepare_image(image_path: str):
    """Return (path_to_send, mime_type), converting PDF first page to PNG if needed."""
    ext = os.path.splitext(image_path)[1].lower()
    if ext == ".pdf":
        png_path = _render_pdf_first_page(image_path)
        return png_path, "image/png"
    mime_type = "image/png" if ext == ".png" else "image/jpeg"
    return image_path, mime_type


def extract_receipt(image_path: str, api_key: Optional[str] = None, model: Optional[str] = None) -> Receipt:
    """Send receipt image (or first page of a PDF) to the vision LLM and parse into Receipt model.
    Tries primary model, falls back to fallback model on failure."""
    key = api_key or os.environ.get("NVIDIA_API_KEY")
    primary_model = model or os.environ.get("NVIDIA_MODEL", "meta/llama-3.2-11b-vision-instruct")
    fallback_model = os.environ.get("NVIDIA_MODEL_FALLBACK", "meta/llama-3.2-90b-vision-instruct")

    if not key or key == "your-key-here" or key == "your-nvidia-api-key-here":
        logger.warning("NVIDIA_API_KEY is not configured. Marking receipt for manual review.")
        return Receipt(
            merchant="Unknown Merchant",
            date=date.today().isoformat(),
            total=0.0,
            subtotal=0.0,
            tax=0.0,
            items=[],
            needs_review=True,
            image_path=image_path,
        )

    try:
        send_path, mime_type = _prepare_image(image_path)

        with open(send_path, "rb") as f:
            image_b64 = base64.b64encode(f.read()).decode("utf-8")

        if send_path != image_path:
            try:
                os.remove(send_path)
            except OSError:
                pass

        models_to_try = [primary_model]
        if fallback_model and fallback_model != primary_model:
            models_to_try.append(fallback_model)

        last_error = None
        for attempt_model in models_to_try:
            try:
                logger.info(f"Attempting extraction with model: {attempt_model}")
                raw_text = _call_nim_vision(key, attempt_model, image_b64, mime_type)
                cleaned = clean_json_response(raw_text)
                parsed = json.loads(cleaned)

                if "merchant" in parsed and parsed["merchant"]:
                    parsed["merchant"] = normalize_merchant(str(parsed["merchant"]))

                parsed["image_path"] = image_path
                receipt = Receipt(**parsed)

                if not validate_totals(receipt):
                    logger.info("Receipt arithmetic mismatch detected. Flagged as needs_review.")
                    receipt.needs_review = True

                return receipt

            except Exception as e:
                last_error = e
                logger.warning(f"Model {attempt_model} failed: {e}")
                continue

        raise last_error

    except Exception as e:
        logger.error(f"Failed to extract receipt from {image_path}: {e}", exc_info=True)
        return Receipt(
            merchant="Unknown Merchant",
            date=date.today().isoformat(),
            total=0.0,
            subtotal=0.0,
            tax=0.0,
            items=[],
            needs_review=True,
            image_path=image_path,
        )
